"""add thread_mappings table

Revision ID: a82772cd469a
Revises: e9e20fcc7660
Create Date: 2026-04-10 01:29:55.959143
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a82772cd469a"
down_revision: str | None = "e9e20fcc7660"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_mappings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pull_request_id", sa.BigInteger(), nullable=False),
        sa.Column("github_thread_id", sa.String(length=255), nullable=False),
        sa.Column("slack_channel_id", sa.String(length=64), nullable=False),
        sa.Column("slack_thread_ts", sa.String(length=64), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_thread_mappings_github_thread_id"),
        "thread_mappings",
        ["github_thread_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thread_mappings_pull_request_id"),
        "thread_mappings",
        ["pull_request_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_thread_mappings_pull_request_id"), table_name="thread_mappings")
    op.drop_index(op.f("ix_thread_mappings_github_thread_id"), table_name="thread_mappings")
    op.drop_table("thread_mappings")
    # ### end Alembic commands ###
