"""initial schema

Revision ID: e9e20fcc7660
Revises:
Create Date: 2026-04-10 01:17:27.374263
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9e20fcc7660"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("github_org_id", sa.BigInteger(), nullable=False),
        sa.Column("github_org_login", sa.String(length=255), nullable=False),
        sa.Column("github_installation_id", sa.BigInteger(), nullable=False),
        sa.Column("slack_team_id", sa.String(length=64), nullable=True),
        sa.Column("slack_team_name", sa.String(length=255), nullable=True),
        sa.Column("slack_bot_token", sa.Text(), nullable=True),
        sa.Column("ci_channel_id", sa.String(length=64), nullable=True),
        sa.Column("recap_channel_id", sa.String(length=64), nullable=True),
        sa.Column("recap_cron", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("github_installation_id"),
        sa.UniqueConstraint("slack_team_id"),
    )
    op.create_index(
        op.f("ix_organizations_github_org_id"), "organizations", ["github_org_id"], unique=True
    )
    op.create_table(
        "pull_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("github_pr_id", sa.BigInteger(), nullable=False),
        sa.Column("github_pr_number", sa.BigInteger(), nullable=False),
        sa.Column("repo_full_name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("head_branch", sa.String(length=255), nullable=False),
        sa.Column("base_branch", sa.String(length=255), nullable=False),
        sa.Column("html_url", sa.Text(), nullable=False),
        sa.Column("author_github_id", sa.BigInteger(), nullable=False),
        sa.Column("author_github_username", sa.String(length=255), nullable=False),
        sa.Column("slack_channel_id", sa.String(length=64), nullable=True),
        sa.Column("no_slack_channel", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pull_requests_author_github_id"),
        "pull_requests",
        ["author_github_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pull_requests_github_pr_id"), "pull_requests", ["github_pr_id"], unique=True
    )
    op.create_index(
        op.f("ix_pull_requests_organization_id"), "pull_requests", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_pull_requests_repo_full_name"), "pull_requests", ["repo_full_name"], unique=False
    )
    op.create_index(
        op.f("ix_pull_requests_slack_channel_id"),
        "pull_requests",
        ["slack_channel_id"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("organization_id", sa.BigInteger(), nullable=False),
        sa.Column("github_user_id", sa.BigInteger(), nullable=False),
        sa.Column("github_username", sa.String(length=255), nullable=False),
        sa.Column("github_access_token", sa.Text(), nullable=True),
        sa.Column("github_refresh_token", sa.Text(), nullable=True),
        sa.Column("github_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("slack_user_id", sa.String(length=64), nullable=True),
        sa.Column("slack_user_name", sa.String(length=255), nullable=True),
        sa.Column("slack_user_token", sa.Text(), nullable=True),
        sa.Column("is_onboarded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_github_user_id"), "users", ["github_user_id"], unique=True)
    op.create_index(op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False)
    op.create_index(op.f("ix_users_slack_user_id"), "users", ["slack_user_id"], unique=True)
    op.create_table(
        "review_time_slots",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("day_of_week", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_review_time_slots_user_id"), "review_time_slots", ["user_id"], unique=False
    )
    op.create_table(
        "slack_channels",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pull_request_id", sa.BigInteger(), nullable=False),
        sa.Column("slack_channel_id", sa.String(length=64), nullable=False),
        sa.Column("slack_channel_name", sa.String(length=80), nullable=False),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["pull_request_id"],
            ["pull_requests.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_slack_channels_pull_request_id"),
        "slack_channels",
        ["pull_request_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_slack_channels_slack_channel_id"),
        "slack_channels",
        ["slack_channel_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_slack_channels_slack_channel_id"), table_name="slack_channels")
    op.drop_index(op.f("ix_slack_channels_pull_request_id"), table_name="slack_channels")
    op.drop_table("slack_channels")
    op.drop_index(op.f("ix_review_time_slots_user_id"), table_name="review_time_slots")
    op.drop_table("review_time_slots")
    op.drop_index(op.f("ix_users_slack_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_users_github_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_pull_requests_slack_channel_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_repo_full_name"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_organization_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_github_pr_id"), table_name="pull_requests")
    op.drop_index(op.f("ix_pull_requests_author_github_id"), table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_organizations_github_org_id"), table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
